---
# tested on el6, el7

- name: register stat of /etc/sysconfig/selinux
  stat: path=/etc/sysconfig/selinux
  register: st

- name: disable selinux
  selinux: policy=targeted state=permissive
  when: st.stat.exists

- name: disable selinux on boot
  lineinfile: dest={{item}} regexp=^SELINUX= line=SELINUX=permissive
  with_items:
    - /etc/sysconfig/selinux
  when: st.stat.exists

- name: install php pkgs
  yum: name={{item}} state=installed
  with_items:
    - php
    - php-mysql
    - php-gd
    - php-mcrypt
    - php-cli
  when: oc_install_php

- name: install httpd pkgs
  yum: name={{item}} state=installed
  with_items:
    - httpd
    - mod_ssl
  when: oc_install_httpd

- name: install unzip
  yum: name={{item}} state=installed
  with_items:
    - unzip

- name: install db server el6
  yum: name={{item}} state=installed
  with_items:
    - MySQL-python
    - mysql-server
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '6' and oc_install_mysqld

- name: install db server el7
  yum: name={{item}} state=installed
  with_items:
    - MySQL-python
    - mariadb-server
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7' and oc_install_mysqld

- name: download opencart to /tmp
  get_url: url={{oc_download_url}} dest=/tmp/opencart-{{oc_version}}.zip

- name: unzip opencart in /tmp
  unarchive: src=/tmp/opencart-{{oc_version}}.zip dest=/tmp copy=no creates=/tmp/opencart-{{oc_version}}

- name: upload opencart into {{oc_web_dir}}
  command: "cp -a /tmp/opencart-{{oc_version}}/upload/{{item}} {{oc_web_dir}}"
  args:
    creates: "{{oc_web_dir}}/admin"
  with_items:
    - catalog
    - crossdomain.xml
    - image
    - index.php
    - php.ini
    - system
    - install
    - admin

- name: touch config-dest.php
  copy: content="" dest={{oc_web_dir}}/{{item}} force=no
  with_items:
    - config.php
    - admin/config.php

- name: chmod g+w and chown apache:apache
  file: path={{oc_web_dir}}/{{item}} owner=apache group=apache mode=0775
  with_items:
    - image
    - image/cache
    - image/catalog
    - system/storage/cache
    - system/storage/logs
    - system/storage/download
    - system/storage/upload
    - system/storage/modification

- name: chmod g+w and chown apache:apache
  file: path={{oc_web_dir}}/{{item}} owner=apache group=apache mode=0664
  with_items:
    - config.php
    - admin/config.php

- name: start webserver
  service: name={{item}} state=started enabled=true
  with_items:
    - httpd

- name: start db server el6
  service: name={{item}} state=started enabled=true
  with_items:
    - mysqld
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '6'

- name: start db server el7
  service: name={{item}} state=started enabled=true
  with_items:
    - mariadb
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'

- name: create opencart db in mysql
  mysql_db: name=opencart state=present

- name: stat {{oc_web_dir}}/install
  stat: path={{oc_web_dir}}/install
  register: st

- name: install opencart
  command: "php {{oc_web_dir}}/install/cli_install.php install --db_hostname {{oc_db_host}} --db_username {{oc_db_user}} --db_password {{oc_db_pass}} --db_database {{oc_db_db}} --db_driver {{oc_db_drv}} --username {{oc_web_user}} --password {{oc_web_pass}} --email {{oc_email}} --http_server {{oc_web_url}}"
  when: st.stat.exists

- name: remove opencart install dir
  file: state=absent dest={{oc_web_dir}}/install

- name: upload images
  copy: src=files/{{item.name}} dest={{oc_web_dir}}/image/catalog/{{item.name}} mode=0664 owner=apache group=apache
  when: item.url is not defined
  with_items: oc_images

- name: download images
  get_url: url={{item.url}} dest={{oc_web_dir}}/image/catalog/{{item.name}} mode=0664 owner=apache group=apache
  when: item.url is defined
  with_items: oc_images
